name: CMake

on: [push, pull_request]
env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        llvm_version: [10, 11, 12, 13]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-${{matrix.llvm_version}}-${{matrix.os}}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "${{matrix.llvm_version}}"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Set LLVM Path (Non-Windows)
        if: "!contains(matrix.os, 'windows')"
        run: echo "CLANG_ROOT=./llvm" >> $GITHUB_ENV

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 8

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
