name: CMake

on: [push, pull_request]
env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        llvm_version: [10, 11, 12, 13]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "${{matrix.llvm_version}}"
          directory: "${{ runner.temp }}/llvm"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 8

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
